In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Semiconductor shortage affects.csv')

In [3]:
df.head()

,DATE,Producer Price Index(By Industry in $),Export Price Index(End Use of semiconductors),Import Price Index(in $ End Use of semiconductors),No. of employed peoples in semiconductor industry,Export Price Index (End use excluding without semiconductors),Relative Importance Weights (Contribution to the Total Industrial Production Index % WISE),"Import Price Index (End Use): Capital Goods, Excluding Computers, Peripherals, and Semiconductors","Export Price Index(End Use): Capital Goods, Excluding Computers, Peripherals, and Semiconductors","Industrial Production: Non-Energy Excluding Motor Vehicles & Parts, Computers, Communications Equipment, and Semiconductors"
0,01-01-1985,100.5,.,.,670.8,.,5.5335,.,NaN,81.4300
1,01-02-1985,100.8,.,.,665.6,.,5.3861,.,NaN,81.4319
2,01-03-1985,100.9,169,141.6,660.9,223.9,5.3103,69.2,NaN,82.1699
3,01-04-1985,100.6,.,.,653.9,.,5.1255,.,NaN,81.9731
4,01-05-1985,100.1,.,.,647.2,.,5.0821,.,NaN,82.1311

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 10 columns):
 #   Column                                                                                                                       Non-Null Count  Dtype
---  ------                                                                                                                       --------------  -----
 0   DATE                                                                                                                         443 non-null    object
 1   Producer Price Index(By  Industry in $)                                                                                      443 non-null    float64
 2   Export Price Index(End Use of semiconductors)                                                                                442 non-null    object
 3   Import Price Index(in $ End Use of semiconductors)                                                                           442 non-null    object
 4   No. of employed peoples in semiconductor industry                                                                            443 non-null    float64
 5   Export Price Index (End use excluding without semiconductors)                                                                442 non-null    object
 6   Relative Importance Weights (Contribution to the Total Industrial Production Index % WISE)                                   442 non-null    float64
 7   Import Price Index (End Use): Capital Goods, Excluding Computers, Peripherals, and Semiconductors                            442 non-null    object
 8   Export Price Index(End Use): Capital Goods, Excluding Computers, Peripherals, and Semiconductors                             239 non-null    float64
 9   Industrial Production: Non-Energy Excluding Motor Vehicles & Parts, Computers, Communications Equipment, and Semiconductors  442 non-null    float64
dtypes: float64(5), object(5)
memory usage: 34.7+ KB

In [7]:
df_bit = pd.read_csv('bitcoin.csv')

In [8]:
df_bit.head()

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
0,1325317920,4.39,4.39,4.39,4.39,0.455581,2.0,4.39
1,1325317980,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1325318040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1325318100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1325318160,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_bit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4857377 entries, 0 to 4857376
Data columns (total 8 columns):
 #   Column             Dtype
---  ------             -----
 0   Timestamp          int64
 1   Open               float64
 2   High               float64
 3   Low                float64
 4   Close              float64
 5   Volume_(BTC)       float64
 6   Volume_(Currency)  float64
 7   Weighted_Price     float64
dtypes: float64(7), int64(1)
memory usage: 296.5 MB

In [12]:
df_bit.describe()

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
count,4.857377e+06,3.613769e+06,3.613769e+06,3.613769e+06,3.613769e+06,3.613769e+06,3.613769e+06,3.613769e+06
mean,1.471301e+09,6.009024e+03,6.013357e+03,6.004488e+03,6.009014e+03,9.323249e+00,4.176284e+04,6.008935e+03
std,8.428019e+07,8.996247e+03,9.003521e+03,8.988778e+03,8.996360e+03,3.054989e+01,1.518248e+05,8.995992e+03
min,1.325318e+09,3.800000e+00,3.800000e+00,1.500000e+00,1.500000e+00,0.000000e+00,0.000000e+00,3.800000e+00
25%,1.398179e+09,4.438600e+02,4.440000e+02,4.435200e+02,4.438600e+02,4.097759e-01,4.521422e+02,4.438306e+02
50%,1.471428e+09,3.596970e+03,3.598190e+03,3.595620e+03,3.597000e+03,1.979811e+00,3.810124e+03,3.596804e+03
75%,1.544288e+09,8.627270e+03,8.632980e+03,8.621090e+03,8.627160e+03,7.278216e+00,2.569821e+04,8.627637e+03
max,1.617149e+09,6.176356e+04,6.178183e+04,6.167355e+04,6.178180e+04,5.853852e+03,1.390067e+07,6.171621e+04

In [13]:
df_btc = pd.read_csv('BTC-USD.csv')

In [14]:
df_btc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       87 non-null     object
 1   Open       87 non-null     float64
 2   High       87 non-null     float64
 3   Low        87 non-null     float64
 4   Close      87 non-null     float64
 5   Adj Close  87 non-null     float64
 6   Volume     87 non-null     int64
dtypes: float64(5), int64(1), object(1)
memory usage: 4.9+ KB

In [36]:
#Arreglando performance de GPU
pd_gpu = pd.read_csv('All_GPUs.csv')

In [37]:
pd_gpu.head()

,Architecture,Best_Resolution,Boost_Clock,Core_Speed,DVI_Connection,Dedicated,Direct_X,DisplayPort_Connection,HDMI_Connection,Integrated,...,Process,ROPs,Release_Date,Release_Price,Resolution_WxH,SLI_Crossfire,Shader,TMUs,Texture_Rate,VGA_Connection
0,Tesla G92b,NaN,NaN,738 MHz,2.0,Yes,DX 10.0,NaN,0.0,No,...,55nm,16,\n01-Mar-2009,NaN,2560x1600,Yes,4.0,64.0,47 GTexel/s,0.0
1,R600 XT,1366 x 768,NaN,\n-,2.0,Yes,DX 10,NaN,0.0,No,...,80nm,16,\n14-May-2007,NaN,2560x1600,Yes,4.0,16.0,12 GTexel/s,0.0
2,R600 PRO,1366 x 768,NaN,\n-,2.0,Yes,DX 10,NaN,0.0,No,...,80nm,16,\n07-Dec-2007,NaN,2560x1600,Yes,4.0,16.0,10 GTexel/s,0.0
3,RV630,1024 x 768,NaN,\n-,2.0,Yes,DX 10,NaN,0.0,No,...,65nm,4,\n01-Jul-2007,NaN,2560x1600,Yes,4.0,8.0,7 GTexel/s,0.0
4,RV630,1024 x 768,NaN,\n-,2.0,Yes,DX 10,NaN,0.0,No,...,65nm,4,\n28-Jun-2007,NaN,2560x1600,Yes,4.0,8.0,6 GTexel/s,0.0

In [38]:
pd_gpu.columns

Index(['Architecture', 'Best_Resolution', 'Boost_Clock', 'Core_Speed',
       'DVI_Connection', 'Dedicated', 'Direct_X', 'DisplayPort_Connection',
       'HDMI_Connection', 'Integrated', 'L2_Cache', 'Manufacturer',
       'Max_Power', 'Memory', 'Memory_Bandwidth', 'Memory_Bus', 'Memory_Speed',
       'Memory_Type', 'Name', 'Notebook_GPU', 'Open_GL', 'PSU', 'Pixel_Rate',
       'Power_Connector', 'Process', 'ROPs', 'Release_Date', 'Release_Price',
       'Resolution_WxH', 'SLI_Crossfire', 'Shader', 'TMUs', 'Texture_Rate',
       'VGA_Connection'],
      dtype='object')

In [39]:
pd_gpu['Memory_Speed'] = pd_gpu['Memory_Speed'].astype(str)

In [40]:
pd_gpu.Memory_Speed

0       1000 MHz
1        828 MHz
2        800 MHz
3       1150 MHz
4        700 MHz
          ...
3401         nan
3402         nan
3403         nan
3404         nan
3405     275 MHz
Name: Memory_Speed, Length: 3406, dtype: object

In [42]:
pd_gpu['Memory_Speed'] = pd_gpu['Memory_Speed'].map(lambda x: x.lstrip(' MHz').rstrip('aAbBcC'))

In [43]:
pd_gpu.Memory_Speed

0       1000 MHz
1        828 MHz
2        800 MHz
3       1150 MHz
4        700 MHz
          ...
3401         nan
3402         nan
3403         nan
3404         nan
3405     275 MHz
Name: Memory_Speed, Length: 3406, dtype: object